name: Build testcases

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt install libfuse2
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: jwlawson/actions-setup-cmake@v2
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
        echo "VESYLA_SUITE_PATH_COMPONENTS=$(pwd)/library" >> $GITHUB_ENV
    - name: Download vesyla-suite-4
      run: gh release download --repo silagokth/vesyla-suite-4 --pattern "vesyla-suite"
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install vesyla-suite
      run: |
        chmod +x vesyla-suite
        mkdir -p /home/runner/.local/bin
        mv vesyla-suite /home/runner/.local/bin
    - name: Assemble testcases
      run: |
        cd testcases
        for testcase in $(ls *.json); do
          vesyla-suite component assemble -a $testcase -o ${testcase%.*}
        done
        ls
    - run: tar czf testcases.tar.gz testcases/
    - name: Upload testcases
      uses: actions/upload-artifact@v2
      with:
        name: testcases
        path: testcases.tar.gz

