name: Build testcases

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt install libfuse2
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: jwlawson/actions-setup-cmake@v2
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
        echo "VESYLA_SUITE_PATH_COMPONENTS=$(pwd)/library" >> $GITHUB_ENV
    - name: Download vesyla-suite-4
      run: gh release download --repo silagokth/vesyla-suite-4 --pattern "vesyla-suite"
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: chmod +x vesyla-suite
    - run: mkdir -p /home/runner/.local/bin
    - run: mv vesyla-suite /home/runner/.local/bin
    - run: echo $PATH
    - name: Assemble one example
      run: |
        cd testcases
        for testcase in $(ls *.json); do
          echo "Assembling $testcase"
          vesyla-suite component assemble -a $testcase -o ${testcase%.*}
        done
        ls
    - run: tar czf testcases.tar.gz testcases/
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: testcases.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
        release_name: ${{ steps.date.outputs.date }}
        tag_name: ${{ steps.date.outputs.date }}
        body: Automated release
        draft: false
        prerelease: false
    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.sha }}
    #     release_name: ${{ github.sha }}
    #     body: |
    #       Automated release
    #     draft: false
    #     prerelease: false
    # - name: Upload Release Asset
    #   id: upload-release-asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: testcases.tar.gz
    #     asset_name: testcases.tar.gz
    #     asset_content_type: application/gzip


