name: Build testcases

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cli/gh-actions@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: jwlawson/actions-setup-cmake@v2
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
        echo "VESYLA_SUITE_PATH_COMPONENTS=$(pwd)/library" >> $GITHUB_ENV
    - name: Assemble one example
      run: |
        cd testcases
        for testcase in $(ls *.json); do
          echo "Assembling $testcase"
          ../build/vesyla_assembler $testcase
        done
    # download release from github.com/silagokth/vesyla-suite-4
    - name: Download vesyla-suite-4
      run: gh release download --repo silagokth/vesyla-suite-4 --pattern "vesyla-suite"
    - run: ls
    - run: echo $PATH


